// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWwwO6GbhMj1QxhANp7ivblq6k9miLMws',
    appId: '1:1019053980950:web:3999077167eb08e25ba437',
    messagingSenderId: '1019053980950',
    projectId: 'fasum-app-2aeef',
    authDomain: 'fasum-app-2aeef.firebaseapp.com',
    databaseURL: 'https://fasum-app-2aeef-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2aeef.firebasestorage.app',
    measurementId: 'G-V70E5CVC1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3jX-l_dPOoBQNGpus2peTYcYBU3uklYE',
    appId: '1:1019053980950:android:690429749fc04e875ba437',
    messagingSenderId: '1019053980950',
    projectId: 'fasum-app-2aeef',
    databaseURL: 'https://fasum-app-2aeef-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2aeef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnlT5OBfHiHr990njDt92ZWld7gcNdT2Y',
    appId: '1:1019053980950:ios:87db8a4c9fbfea995ba437',
    messagingSenderId: '1019053980950',
    projectId: 'fasum-app-2aeef',
    databaseURL: 'https://fasum-app-2aeef-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2aeef.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnlT5OBfHiHr990njDt92ZWld7gcNdT2Y',
    appId: '1:1019053980950:ios:87db8a4c9fbfea995ba437',
    messagingSenderId: '1019053980950',
    projectId: 'fasum-app-2aeef',
    databaseURL: 'https://fasum-app-2aeef-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2aeef.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWwwO6GbhMj1QxhANp7ivblq6k9miLMws',
    appId: '1:1019053980950:web:877fa9e7e382f5a65ba437',
    messagingSenderId: '1019053980950',
    projectId: 'fasum-app-2aeef',
    authDomain: 'fasum-app-2aeef.firebaseapp.com',
    databaseURL: 'https://fasum-app-2aeef-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2aeef.firebasestorage.app',
    measurementId: 'G-DSV8CSEVPS',
  );

}